import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import LandingNavBar from "@/components/LandingNavbar";
import LandingFooter from "@/components/LandingFooter";
import { Poppins } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={poppins.className}>
        <body>
          <nav>
            <LandingNavBar />
          </nav>
          {children}
          <LandingFooter />
        </body>
      </html>
    </ClerkProvider>
  );
}
