import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import LandingNavBar from "@/components/LandingNavbar";
import LandingFooter from "@/components/LandingFooter";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
          rel="stylesheet"
        />
        <body>
          <nav>
            <LandingNavBar />
          </nav>
          {children}
          <LandingFooter />
        </body>
      </html>
    </ClerkProvider>
  );
}
